### ISSUE TITLE
大神，请教一下

### ISSUE THREAD

**Issue by hulingjie** [SunQilin/lstm_matlab#3]
@SunQilin 大神，我训练这个LSTM神经网络用于分类，但是训练过后，发现将训练样本放入测试，竟然识别率竟然非常低，照理来说训练样本在测试的时候识别率应该很高啊。我想问一下，这是网络哪里出现了问题？求指教..QQ：308371937  邮箱：308371937 @qq.com

**Comment by SunQilin** [comment]
请给出具体问题和建模方式

**Comment by hulingjie** [comment]
因为我是初次接触，没有修改网络。我要把数据分成20个类别，所以我把toyexample中的len_out改为20，X改成我要训练的数据，Y作为训练样本的标签（标签与x一一对应，一个标签一共20个数由01编码组成），然后进行训练。训练完后，将测试样本放入lstmcellff（已经训练过的网络）进行测试。我这样做对吗？新人尝试，请指教

**Comment by SunQilin** [comment]
lstm是时序性网络，你这样用是不行的。你现在用法相当于样本之间是时序性关系，每个样本是网络某个时刻输入，样本1是网络在第一个时刻的输入，然后样本2是第二个时刻输入等等，这应该不是你想刻画的形式吧？

**Comment by hulingjie** [comment]
我是按时序训练的，我所有的训练样本是放在一个cell矩阵中的，cell中的每个元素都是n×m的矩阵，n就是时间长度t，m指的就是特征个数（n是变化的因为样本的时间长度是不同的，但m是固定的每个样本的特征数量是相同的）。我训练的时候就是循环的去调用cell中的元素，每调用一个元素我就创建一个与之相对应标签Y，然后进行训练。

**Comment by SunQilin** [comment]
标签Y 是一个n*1的向量？如果标签是1，Y中每个元素都是1，否则Y中每个元素都是0？

**Comment by hulingjie** [comment]
因为调用的元素是n_m的矩阵（一个样本），那我建立的标签Y一个是n_20的矩阵，因为后面要进行（e = y - lstmcell.mh）误差计算。上面我提到过我要分20个类别，由01编码组成20个数。举个例子，如果我从cell中读取30*50的矩阵(属于第一类)，那么我的标签Y就是30×20的矩阵，30×[1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 ]，属于第几个类那第几个数为1其余为0。可以加下QQ吗？这样方便交流：308371937
